[package]
name = "noirblanc_core"
version = "0.1.0"
authors = ["koba-e964 <3303362+koba-e964@users.noreply.github.com>"]
edition = "2021"
publish = false
rust-version = "1.74"

[dev-dependencies]
criterion = "0.5"

[lib]
bench = false

[[bench]]
name = "perft"
harness = false
